from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional, Tuple


TEMPLATES_ROOT = Path(__file__).resolve().parents[2] / "templates"
CUSTOM_ROOT = TEMPLATES_ROOT / "custom"


def sanitize_template_id(value: str) -> str:
    raw = (value or "").strip().lower().replace(" ", "_")
    raw = re.sub(r"[^a-z0-9_-]+", "", raw)
    raw = raw.strip("_-")
    return raw or "custom_template"


def ensure_unique_template_id(template_id: str, root: Path) -> str:
    if not (root / template_id).exists():
        return template_id
    i = 2
    while (root / f"{template_id}_{i}").exists():
        i += 1
    return f"{template_id}_{i}"


@dataclass
class TextSpec:
    enabled: bool
    max_lines: int
    line1: str
    line2: str
    line3: str
    text_size: float
    text_height: float
    line_gap: float
    pad_x: float
    pad_y: float
    offset_x: float = 0.0
    offset_y: float = 0.0
    emboss: int = 1
    text_align: str = "center"


@dataclass
class EmblemSpec:
    enabled: bool
    snap: str
    autocenter: int
    scale: float
    depth: float
    x: float
    y: float
    rot: float
    mode: int


@dataclass
class TemplateSpec:
    template_id: str
    label: str
    shape: str  # rounded_rect | circle
    width: float
    height: float
    diameter: float
    thickness: float
    radius: float
    text: Optional[TextSpec]
    emblem: Optional[EmblemSpec]


def _build_scad(spec: TemplateSpec) -> str:
    lines = []
    lines.append("// Auto-generated by Template Builder")
    if spec.shape == "rounded_rect":
        lines.append(f"w = {spec.width};")
        lines.append(f"h = {spec.height};")
        lines.append(f"r = {spec.radius};")
    else:
        lines.append(f"d = {spec.diameter};")
    lines.append(f"th = {spec.thickness};")
    lines.append("")

    if spec.text:
        t = spec.text
        lines.extend([
            f'line1 = "{t.line1}";',
            f'line2 = "{t.line2}";',
            f'line3 = "{t.line3}";',
            f"line_gap = {t.line_gap};",
            f"offset_x = {t.offset_x};",
            f"offset_y = {t.offset_y};",
            f"text_enabled = {1 if t.enabled else 0};",
            f'text_align = "{t.text_align}";',
            f"text_size = {t.text_size};",
            f"text_height = {t.text_height};",
            f"emboss = {t.emboss};",
            "",
        ])

    if spec.emblem:
        e = spec.emblem
        lines.extend([
            "emblem_path = \"\";",
            f"emblem_enabled = {1 if e.enabled else 0};",
            f"emblem_scale = {e.scale};",
            f"emblem_x = {e.x};",
            f"emblem_y = {e.y};",
            f"emblem_rot = {e.rot};",
            f"emblem_mode = {e.mode};",
            f"emblem_depth = {e.depth};",
            "",
        ])

    lines.append("$fn = 64;")
    lines.append("")

    if spec.shape == "rounded_rect":
        lines.extend([
            "module rounded_rect_2d(width, height, radius) {",
            "  r_eff = min(radius, min(width, height) / 2);",
            "  hull() {",
            "    translate([ width/2 - r_eff,  height/2 - r_eff]) circle(r=r_eff);",
            "    translate([-width/2 + r_eff,  height/2 - r_eff]) circle(r=r_eff);",
            "    translate([ width/2 - r_eff, -height/2 + r_eff]) circle(r=r_eff);",
            "    translate([-width/2 + r_eff, -height/2 + r_eff]) circle(r=r_eff);",
            "  }",
            "}",
            "",
            "module base_shape() {",
            "  linear_extrude(height=th)",
            "    rounded_rect_2d(w, h, r);",
            "}",
            "",
        ])
    else:
        lines.extend([
            "module base_shape() {",
            "  linear_extrude(height=th)",
            "    circle(d=d);",
            "}",
            "",
        ])

    if spec.text:
        lines.extend([
            "module line_text_3d(s, y) {",
            "  translate([offset_x, offset_y + y, 0])",
            "    linear_extrude(height=text_height)",
            "      text(s, size=text_size, halign=text_align, valign=\"center\");",
            "}",
            "",
            "module text_union() {",
            "  if (text_enabled == 1) {",
            "    if (line2 == \"\" && line3 == \"\") {",
            "      line_text_3d(line1, 0);",
            "    } else if (line3 == \"\") {",
            "      line_text_3d(line1, line_gap / 2);",
            "      line_text_3d(line2, -line_gap / 2);",
            "    } else {",
            "      line_text_3d(line1, line_gap);",
            "      line_text_3d(line2, 0);",
            "      line_text_3d(line3, -line_gap);",
            "    }",
            "  }",
            "}",
            "",
        ])

    if spec.emblem:
        lines.extend([
            "module emblem_3d(z) {",
            "  if (emblem_enabled == 1 && emblem_path != \"\") {",
            "    translate([emblem_x, emblem_y, z])",
            "      rotate([0, 0, emblem_rot])",
            "        scale([emblem_scale, emblem_scale, 1])",
            "          linear_extrude(height=emblem_depth)",
            "            import(emblem_path);",
            "  }",
            "}",
            "",
        ])

    lines.append("difference() {")
    lines.append("  base_shape();")
    if spec.text:
        lines.append("  if (emboss == 0) {")
        lines.append("    translate([0, 0, th - text_height]) text_union();")
        lines.append("  }")
    if spec.emblem:
        lines.append("  if (emblem_mode == 0) {")
        lines.append("    emblem_3d(th - emblem_depth);")
        lines.append("  }")
    lines.append("}")
    lines.append("")

    if spec.text:
        lines.append("if (emboss == 1) {")
        lines.append("  translate([0, 0, th]) text_union();")
        lines.append("}")
        lines.append("")

    if spec.emblem:
        lines.append("if (emblem_mode == 1) {")
        lines.append("  emblem_3d(th);")
        lines.append("}")

    return "\n".join(lines) + "\n"


def _build_schema(spec: TemplateSpec) -> Dict[str, Any]:
    params: Dict[str, Any] = {}
    if spec.shape == "rounded_rect":
        params.update({
            "w": {"type": "number", "default": spec.width, "min": 10, "max": 400},
            "h": {"type": "number", "default": spec.height, "min": 10, "max": 400},
            "r": {"type": "number", "default": spec.radius, "min": 0, "max": 200},
        })
    else:
        params.update({
            "d": {"type": "number", "default": spec.diameter, "min": 10, "max": 400},
        })
    params.update({
        "th": {"type": "number", "default": spec.thickness, "min": 1, "max": 50},
    })

    schema: Dict[str, Any] = {
        "template_id": f"custom/{spec.template_id}",
        "label": spec.label,
        "scad_file": "model.scad",
        "params": params,
    }

    if spec.text:
        t = spec.text
        params.update({
            "text_enabled": {"type": "integer", "default": 1, "min": 0, "max": 1},
            "line1": {"type": "string", "default": t.line1},
            "line2": {"type": "string", "default": t.line2},
            "line3": {"type": "string", "default": t.line3},
            "text_size": {"type": "number", "default": t.text_size, "min": 4, "max": 60},
            "text_height": {"type": "number", "default": t.text_height, "min": 0.2, "max": 10},
            "line_gap": {"type": "number", "default": t.line_gap, "min": 0, "max": 60},
            "offset_x": {"type": "number", "default": t.offset_x, "min": -200, "max": 200},
            "offset_y": {"type": "number", "default": t.offset_y, "min": -200, "max": 200},
            "emboss": {"type": "integer", "default": t.emboss, "min": 0, "max": 1},
            "text_align": {"type": "string", "default": t.text_align},
            "pad_x": {"type": "number", "default": t.pad_x, "min": 0, "max": 200},
            "pad_y": {"type": "number", "default": t.pad_y, "min": 0, "max": 200},
        })

        if spec.shape == "rounded_rect":
            box_w_expr = "w - 2*pad_x"
            box_h_expr = "h - 2*pad_y"
        else:
            box_w_expr = "d - 2*pad_x"
            box_h_expr = "d - 2*pad_y"
        schema["max_lines"] = t.max_lines
        schema["text_box"] = {
            "box_w": box_w_expr,
            "box_h": box_h_expr,
            "offset_x": 0,
            "offset_y": 0,
        }
    elif spec.emblem:
        if spec.shape == "rounded_rect":
            box_w_expr = "w - 2*pad_x"
            box_h_expr = "h - 2*pad_y"
        else:
            box_w_expr = "d - 2*pad_x"
            box_h_expr = "d - 2*pad_y"
        params.update({
            "pad_x": {"type": "number", "default": 0.0, "min": 0, "max": 200},
            "pad_y": {"type": "number", "default": 0.0, "min": 0, "max": 200},
        })
        schema["text_box"] = {
            "box_w": box_w_expr,
            "box_h": box_h_expr,
            "offset_x": 0,
            "offset_y": 0,
        }

    if spec.emblem:
        e = spec.emblem
        params.update({
            "emblem_snap": {"type": "string", "default": e.snap},
            "emblem_autocenter": {"type": "integer", "default": e.autocenter, "min": 0, "max": 1},
            "emblem_enabled": {"type": "integer", "default": 0, "min": 0, "max": 1},
            "emblem_path": {"type": "string", "default": ""},
            "emblem_scale": {"type": "number", "default": e.scale, "min": 0.05, "max": 5},
            "emblem_x": {"type": "number", "default": e.x, "min": -200, "max": 200},
            "emblem_y": {"type": "number", "default": e.y, "min": -200, "max": 200},
            "emblem_rot": {"type": "number", "default": e.rot, "min": -180, "max": 180},
            "emblem_mode": {"type": "integer", "default": e.mode, "min": 0, "max": 1},
            "emblem_depth": {"type": "number", "default": e.depth, "min": 0.2, "max": 10},
        })

    return schema


def _build_meta(spec: TemplateSpec) -> Dict[str, Any]:
    return {
        "template_id": f"custom/{spec.template_id}",
        "label": spec.label,
        "builder_version": 1,
        "shape": spec.shape,
        "text_enabled": bool(spec.text),
        "emblem_enabled": bool(spec.emblem),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "defaults": asdict(spec),
    }


def create_template(spec: TemplateSpec) -> Tuple[str, Path]:
    CUSTOM_ROOT.mkdir(parents=True, exist_ok=True)
    template_id = sanitize_template_id(spec.template_id)
    template_id = ensure_unique_template_id(template_id, CUSTOM_ROOT)
    spec.template_id = template_id

    out_dir = CUSTOM_ROOT / template_id
    out_dir.mkdir(parents=True, exist_ok=False)

    scad_path = out_dir / "model.scad"
    schema_path = out_dir / "schema.json"
    meta_path = out_dir / "meta.json"

    scad_path.write_text(_build_scad(spec))
    schema_path.write_text(json.dumps(_build_schema(spec), indent=2))
    meta_path.write_text(json.dumps(_build_meta(spec), indent=2))
    return template_id, out_dir
