from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional, Tuple


TEMPLATES_ROOT = Path(__file__).resolve().parents[2] / "templates"
CUSTOM_ROOT = TEMPLATES_ROOT / "custom"


def sanitize_template_id(value: str) -> str:
    raw = (value or "").strip().lower().replace(" ", "_")
    raw = re.sub(r"[^a-z0-9_-]+", "", raw)
    raw = raw.strip("_-")
    return raw or "custom_template"


def ensure_unique_template_id(template_id: str, root: Path) -> str:
    if not (root / template_id).exists():
        return template_id
    i = 2
    while (root / f"{template_id}_{i}").exists():
        i += 1
    return f"{template_id}_{i}"


@dataclass
class TextSpec:
    enabled: bool
    max_lines: int
    line1: str
    line2: str
    line3: str
    text_size: float
    text_height: float
    line_gap: float
    pad_x: float
    pad_y: float
    offset_x: float = 0.0
    offset_y: float = 0.0
    emboss: int = 1
    text_align: str = "center"


@dataclass
class EmblemSpec:
    enabled: bool
    snap: str
    autocenter: int
    scale: float
    depth: float
    x: float
    y: float
    rot: float
    mode: int


@dataclass
class TemplateSpec:
    template_id: str
    label: str
    shape: str  # rounded_rect | circle
    width: float
    height: float
    diameter: float
    thickness: float
    radius: float
    text: Optional[TextSpec]
    emblem: Optional[EmblemSpec]


def _build_scad(spec: TemplateSpec) -> str:
    lines = []
    lines.append("// Auto-generated by Template Builder")
    if spec.shape == "rounded_rect":
        lines.append(f"w = {spec.width};")
        lines.append(f"h = {spec.height};")
        lines.append(f"r = {spec.radius};")
    else:
        lines.append(f"d = {spec.diameter};")
    lines.append(f"th = {spec.thickness};")
    lines.append("")

    if spec.text:
        t = spec.text
        lines.extend([
            f'line1 = "{t.line1}";',
            f'line2 = "{t.line2}";',
            f'line3 = "{t.line3}";',
            f"line_gap = {t.line_gap};",
            f"offset_x = {t.offset_x};",
            f"offset_y = {t.offset_y};",
            f"text_enabled = {1 if t.enabled else 0};",
            f'text_align = "{t.text_align}";',
            f"text_size = {t.text_size};",
            f"text_height = {t.text_height};",
            f"emboss = {t.emboss};",
            "",
        ])

    if spec.emblem:
        e = spec.emblem
        lines.extend([
            "emblem_path = \"\";",
            f"emblem_enabled = {1 if e.enabled else 0};",
            f"emblem_scale = {e.scale};",
            f"emblem_x = {e.x};",
            f"emblem_y = {e.y};",
            f"emblem_rot = {e.rot};",
            f"emblem_mode = {e.mode};",
            f"emblem_depth = {e.depth};",
            "",
        ])

    lines.append("$fn = 64;")
    lines.append("")

    if spec.shape == "rounded_rect":
        lines.extend([
            "module rounded_rect_2d(width, height, radius) {",
            "  r_eff = min(radius, min(width, height) / 2);",
            "  hull() {",
            "    translate([ width/2 - r_eff,  height/2 - r_eff]) circle(r=r_eff);",
            "    translate([-width/2 + r_eff,  height/2 - r_eff]) circle(r=r_eff);",
            "    translate([ width/2 - r_eff, -height/2 + r_eff]) circle(r=r_eff);",
            "    translate([-width/2 + r_eff, -height/2 + r_eff]) circle(r=r_eff);",
            "  }",
            "}",
            "",
            "module base_shape() {",
            "  linear_extrude(height=th)",
            "    rounded_rect_2d(w, h, r);",
            "}",
            "",
        ])
    else:
        lines.extend([
            "module base_shape() {",
            "  linear_extrude(height=th)",
            "    circle(d=d);",
            "}",
            "",
        ])

    if spec.text:
        lines.extend([
            "module line_text_3d(s, y) {",
            "  translate([offset_x, offset_y + y, 0])",
            "    linear_extrude(height=text_height)",
            "      text(s, size=text_size, halign=text_align, valign=\"center\");",
            "}",
            "",
            "module text_union() {",
            "  if (text_enabled == 1) {",
            "    if (line2 == \"\" && line3 == \"\") {",
            "      line_text_3d(line1, 0);",
            "    } else if (line3 == \"\") {",
            "      line_text_3d(line1, line_gap / 2);",
            "      line_text_3d(line2, -line_gap / 2);",
            "    } else {",
            "      line_text_3d(line1, line_gap);",
            "      line_text_3d(line2, 0);",
            "      line_text_3d(line3, -line_gap);",
            "    }",
            "  }",
            "}",
            "",
        ])

    if spec.emblem:
        lines.extend([
            "module emblem_3d(z) {",
            "  if (emblem_enabled == 1 && emblem_path != \"\") {",
            "    translate([emblem_x, emblem_y, z])",
            "      rotate([0, 0, emblem_rot])",
            "        scale([emblem_scale, emblem_scale, 1])",
            "          linear_extrude(height=emblem_depth)",
            "            import(emblem_path);",
            "  }",
            "}",
            "",
        ])

    lines.append("difference() {")
    lines.append("  base_shape();")
    if spec.text:
        lines.append("  if (emboss == 0) {")
        lines.append("    translate([0, 0, th - text_height]) text_union();")
        lines.append("  }")
    if spec.emblem:
        lines.append("  if (emblem_mode == 0) {")
        lines.append("    emblem_3d(th - emblem_depth);")
        lines.append("  }")
    lines.append("}")
    lines.append("")

    if spec.text:
        lines.append("if (emboss == 1) {")
        lines.append("  translate([0, 0, th]) text_union();")
        lines.append("}")
        lines.append("")

    if spec.emblem:
        lines.append("if (emblem_mode == 1) {")
        lines.append("  emblem_3d(th);")
        lines.append("}")

    return "\n".join(lines) + "\n"


def _build_schema(spec: TemplateSpec) -> Dict[str, Any]:
    params: Dict[str, Any] = {}
    if spec.shape == "rounded_rect":
        params.update({
            "w": {"type": "number", "default": spec.width, "min": 10, "max": 400},
            "h": {"type": "number", "default": spec.height, "min": 10, "max": 400},
            "r": {"type": "number", "default": spec.radius, "min": 0, "max": 200},
        })
    else:
        params.update({
            "d": {"type": "number", "default": spec.diameter, "min": 10, "max": 400},
        })
    params.update({
        "th": {"type": "number", "default": spec.thickness, "min": 1, "max": 50},
    })

    schema: Dict[str, Any] = {
        "template_id": f"custom/{spec.template_id}",
        "label": spec.label,
        "scad_file": "model.scad",
        "params": params,
    }

    if spec.text:
        t = spec.text
        params.update({
            "text_enabled": {"type": "integer", "default": 1, "min": 0, "max": 1},
            "line1": {"type": "string", "default": t.line1},
            "line2": {"type": "string", "default": t.line2},
            "line3": {"type": "string", "default": t.line3},
            "text_size": {"type": "number", "default": t.text_size, "min": 4, "max": 60},
            "text_height": {"type": "number", "default": t.text_height, "min": 0.2, "max": 10},
            "line_gap": {"type": "number", "default": t.line_gap, "min": 0, "max": 60},
            "offset_x": {"type": "number", "default": t.offset_x, "min": -200, "max": 200},
            "offset_y": {"type": "number", "default": t.offset_y, "min": -200, "max": 200},
            "emboss": {"type": "integer", "default": t.emboss, "min": 0, "max": 1},
            "text_align": {"type": "string", "default": t.text_align, "options": ["left", "center", "right"]},
            "pad_x": {"type": "number", "default": t.pad_x, "min": 0, "max": 200},
            "pad_y": {"type": "number", "default": t.pad_y, "min": 0, "max": 200},
        })

        if spec.shape == "rounded_rect":
            box_w_expr = "w - 2*pad_x"
            box_h_expr = "h - 2*pad_y"
        else:
            box_w_expr = "d - 2*pad_x"
            box_h_expr = "d - 2*pad_y"
        schema["max_lines"] = t.max_lines
        schema["text_box"] = {
            "box_w": box_w_expr,
            "box_h": box_h_expr,
            "offset_x": 0,
            "offset_y": 0,
        }
    elif spec.emblem:
        if spec.shape == "rounded_rect":
            box_w_expr = "w - 2*pad_x"
            box_h_expr = "h - 2*pad_y"
        else:
            box_w_expr = "d - 2*pad_x"
            box_h_expr = "d - 2*pad_y"
        params.update({
            "pad_x": {"type": "number", "default": 0.0, "min": 0, "max": 200},
            "pad_y": {"type": "number", "default": 0.0, "min": 0, "max": 200},
        })
        schema["text_box"] = {
            "box_w": box_w_expr,
            "box_h": box_h_expr,
            "offset_x": 0,
            "offset_y": 0,
        }

    if spec.emblem:
        e = spec.emblem
        params.update({
            "emblem_snap": {
                "type": "string",
                "default": e.snap,
                "options": [
                    "custom",
                    "center",
                    "left",
                    "right",
                    "above_text",
                    "below_text",
                    "top_left",
                    "top_right",
                    "bottom_left",
                    "bottom_right",
                ],
            },
            "emblem_autocenter": {"type": "integer", "default": e.autocenter, "min": 0, "max": 1},
            "emblem_enabled": {"type": "integer", "default": 0, "min": 0, "max": 1},
            "emblem_path": {"type": "string", "default": ""},
            "emblem_scale": {"type": "number", "default": e.scale, "min": 0.05, "max": 5},
            "emblem_x": {"type": "number", "default": e.x, "min": -200, "max": 200},
            "emblem_y": {"type": "number", "default": e.y, "min": -200, "max": 200},
            "emblem_rot": {"type": "number", "default": e.rot, "min": -180, "max": 180},
            "emblem_mode": {"type": "integer", "default": e.mode, "min": 0, "max": 1},
            "emblem_depth": {"type": "number", "default": e.depth, "min": 0.2, "max": 10},
        })

    return schema


def _build_meta(spec: TemplateSpec) -> Dict[str, Any]:
    return {
        "template_id": f"custom/{spec.template_id}",
        "label": spec.label,
        "builder_version": 1,
        "shape": spec.shape,
        "text_enabled": bool(spec.text),
        "emblem_enabled": bool(spec.emblem),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "defaults": asdict(spec),
    }


def create_template(spec: TemplateSpec) -> Tuple[str, Path]:
    CUSTOM_ROOT.mkdir(parents=True, exist_ok=True)
    template_id = sanitize_template_id(spec.template_id)
    template_id = ensure_unique_template_id(template_id, CUSTOM_ROOT)
    spec.template_id = template_id

    out_dir = CUSTOM_ROOT / template_id
    out_dir.mkdir(parents=True, exist_ok=False)

    scad_path = out_dir / "model.scad"
    schema_path = out_dir / "schema.json"
    meta_path = out_dir / "meta.json"

    scad_path.write_text(_build_scad(spec))
    schema_path.write_text(json.dumps(_build_schema(spec), indent=2))
    meta_path.write_text(json.dumps(_build_meta(spec), indent=2))
    return template_id, out_dir


def spec_to_defaults(spec: TemplateSpec) -> Dict[str, Any]:
    return {
        "template_id": spec.template_id,
        "label": spec.label,
        "shape": spec.shape,
        "width": spec.width,
        "height": spec.height,
        "diameter": spec.diameter,
        "thickness": spec.thickness,
        "radius": spec.radius,
        "text": asdict(spec.text) if spec.text else None,
        "emblem": asdict(spec.emblem) if spec.emblem else None,
    }


def _clamp(value: Any, min_v: float, max_v: float, default: float) -> float:
    try:
        num = float(value)
    except Exception:
        return float(default)
    return float(max(min_v, min(max_v, num)))


def coerce_template_spec(data: Dict[str, Any]) -> TemplateSpec:
    data = data or {}
    shape = str(data.get("shape", "rounded_rect")).strip().lower()
    if shape not in {"rounded_rect", "circle"}:
        shape = "rounded_rect"

    template_id = sanitize_template_id(str(data.get("template_id", "custom_template")))
    label = str(data.get("label") or template_id).strip() or template_id

    width = _clamp(data.get("width", 80), 10, 400, 80)
    height = _clamp(data.get("height", 30), 10, 400, 30)
    diameter = _clamp(data.get("diameter", 70), 10, 400, 70)
    thickness = _clamp(data.get("thickness", 4), 1, 50, 4)
    radius = _clamp(data.get("radius", 5), 0, 200, 5)
    radius = min(radius, min(width, height) / 2) if shape == "rounded_rect" else 0.0

    text_spec = None
    text_data = data.get("text") or None
    if isinstance(text_data, dict) and text_data.get("enabled", True):
        max_lines = int(_clamp(text_data.get("max_lines", 2), 1, 3, 2))
        line1 = str(text_data.get("line1", "YOUR TEXT"))
        line2 = str(text_data.get("line2", "")) if max_lines >= 2 else ""
        line3 = str(text_data.get("line3", "")) if max_lines >= 3 else ""
        text_spec = TextSpec(
            enabled=True,
            max_lines=max_lines,
            line1=line1,
            line2=line2,
            line3=line3,
            text_size=_clamp(text_data.get("text_size", 12), 4, 60, 12),
            text_height=_clamp(text_data.get("text_height", 1.2), 0.2, 10, 1.2),
            line_gap=_clamp(text_data.get("line_gap", 8), 0, 60, 8),
            pad_x=_clamp(text_data.get("pad_x", 6), 0, 200, 6),
            pad_y=_clamp(text_data.get("pad_y", 4), 0, 200, 4),
            offset_x=_clamp(text_data.get("offset_x", 0), -200, 200, 0),
            offset_y=_clamp(text_data.get("offset_y", 0), -200, 200, 0),
            emboss=1 if str(text_data.get("emboss", 1)) in {"1", "true", "True"} else 0,
            text_align=str(text_data.get("text_align", "center")).lower()
            if str(text_data.get("text_align", "center")).lower() in {"left", "center", "right"}
            else "center",
        )

    emblem_spec = None
    emblem_data = data.get("emblem") or None
    if isinstance(emblem_data, dict) and emblem_data.get("enabled", True):
        snap = str(emblem_data.get("snap", "custom"))
        if snap not in {
            "custom",
            "center",
            "left",
            "right",
            "above_text",
            "below_text",
            "top_left",
            "top_right",
            "bottom_left",
            "bottom_right",
        }:
            snap = "custom"
        emblem_spec = EmblemSpec(
            enabled=True,
            snap=snap,
            autocenter=1 if str(emblem_data.get("autocenter", 1)) in {"1", "true", "True"} else 0,
            scale=_clamp(emblem_data.get("scale", 0.25), 0.05, 5, 0.25),
            depth=_clamp(emblem_data.get("depth", 1.2), 0.2, 10, 1.2),
            x=_clamp(emblem_data.get("x", 0), -200, 200, 0),
            y=_clamp(emblem_data.get("y", 0), -200, 200, 0),
            rot=_clamp(emblem_data.get("rot", 0), -180, 180, 0),
            mode=1 if str(emblem_data.get("mode", 1)) in {"1", "true", "True"} else 0,
        )

    return TemplateSpec(
        template_id=template_id,
        label=label,
        shape=shape,
        width=width,
        height=height,
        diameter=diameter,
        thickness=thickness,
        radius=radius,
        text=text_spec,
        emblem=emblem_spec,
    )
